import { createHash } from "node:crypto";
import { SKILL_MD, SKILL_NAME, SKILL_INDEX_DESCRIPTION } from "@/lib/skill";

/**
 * The discovery index for Swamp's Agent Skill, built from the artifact itself.
 *
 * The convention (Agent Skills Discovery, draft 0.2.0) requires a SHA-256 digest
 * of the exact bytes served at the artifact URL, formatted `sha256:{hex}`. That
 * digest is computed here, at request time, from the same string the artifact
 * route serves. It is not typed in and not generated by a build step, for the
 * same reason nothing else in this repository writes a count by hand: a digest
 * that stops matching its file turns a client's mandatory integrity check into a
 * refusal, and it would do so silently, on the day the skill changed.
 *
 * `$schema` is the version marker the spec tells clients to match on. It is the
 * 0.2.0 URI because this index carries the 0.2.0 fields (`type`, `url`, `digest`);
 * an index missing it would be read as the superseded 0.1 format, whose shape this
 * is not. The doc comment on the route explains why the artifact is also aliased
 * at the older path.
 */

export const AGENT_SKILLS_SCHEMA =
  "https://schemas.agentskills.io/discovery/0.2.0/schema.json";

/** SHA-256 of the raw bytes of the served artifact, in the spec's format. */
export function skillDigest(): string {
  return `sha256:${createHash("sha256").update(SKILL_MD, "utf8").digest("hex")}`;
}

/** The canonical artifact URL: where a client that read the index goes next. */
export const SKILL_ARTIFACT_URL = `/.well-known/agent-skills/${SKILL_NAME}/SKILL.md`;

/** The superseded 0.1 path, kept so a client that guessed it is answered. */
export const LEGACY_SKILL_ARTIFACT_URL = `/.well-known/skills/${SKILL_NAME}/SKILL.md`;

/**
 * One skill entry. The description is the frontmatter's, so what a client reads at
 * level 1 cannot disagree with what it reads after loading the body.
 */
export function skillIndexEntry(artifactUrl = SKILL_ARTIFACT_URL) {
  return {
    name: SKILL_NAME,
    type: "skill-md" as const,
    description: SKILL_INDEX_DESCRIPTION,
    url: artifactUrl,
    digest: skillDigest(),
  };
}

/** The whole index document, ready to serialise. */
export function skillIndex(artifactUrl = SKILL_ARTIFACT_URL) {
  return {
    $schema: AGENT_SKILLS_SCHEMA,
    skills: [skillIndexEntry(artifactUrl)],
  };
}
