import { createHash } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import { SKILL_MD, SKILL_NAME, SKILL_INDEX_DESCRIPTION } from "@/lib/skill";
import { digestOf, listResidentSkills, type ResidentSkill } from "@/lib/swamp/skills";

/**
 * The discovery index for Swamp's Agent Skill, built from the artifact itself.
 *
 * The convention (Agent Skills Discovery, draft 0.2.0) requires a SHA-256 digest
 * of the exact bytes served at the artifact URL, formatted `sha256:{hex}`. That
 * digest is computed here, at request time, from the same string the artifact
 * route serves. It is not typed in and not generated by a build step, for the
 * same reason nothing else in this repository writes a count by hand: a digest
 * that stops matching its file turns a client's mandatory integrity check into a
 * refusal, and it would do so silently, on the day the skill changed.
 *
 * `$schema` is the version marker the spec tells clients to match on. It is the
 * 0.2.0 URI because this index carries the 0.2.0 fields (`type`, `url`, `digest`);
 * an index missing it would be read as the superseded 0.1 format, whose shape this
 * is not. The doc comment on the route explains why the artifact is also aliased
 * at the older path.
 */

export const AGENT_SKILLS_SCHEMA =
  "https://schemas.agentskills.io/discovery/0.2.0/schema.json";

/** SHA-256 of the raw bytes of the served artifact, in the spec's format. */
export function skillDigest(): string {
  return `sha256:${createHash("sha256").update(SKILL_MD, "utf8").digest("hex")}`;
}

/** The canonical artifact URL: where a client that read the index goes next. */
export const SKILL_ARTIFACT_URL = `/.well-known/agent-skills/${SKILL_NAME}/SKILL.md`;

/** The superseded 0.1 path, kept so a client that guessed it is answered. */
export const LEGACY_SKILL_ARTIFACT_URL = `/.well-known/skills/${SKILL_NAME}/SKILL.md`;

/**
 * One skill entry. The description is the frontmatter's, so what a client reads at
 * level 1 cannot disagree with what it reads after loading the body.
 */
export function skillIndexEntry(artifactUrl = SKILL_ARTIFACT_URL) {
  return {
    name: SKILL_NAME,
    type: "skill-md" as const,
    description: SKILL_INDEX_DESCRIPTION,
    url: artifactUrl,
    digest: skillDigest(),
  };
}

/** The whole index document, ready to serialise. */
export function skillIndex(artifactUrl = SKILL_ARTIFACT_URL) {
  return {
    $schema: AGENT_SKILLS_SCHEMA,
    skills: [skillIndexEntry(artifactUrl)],
  };
}

/**
 * The swarm's own skills, as index entries.
 *
 * This is what turns the marketplace from the platform's single skill into the
 * swarm's catalogue. A runtime that reads this index and nothing else sees every
 * skill residents have written, each pointing at bytes this host serves and
 * commits to by digest.
 *
 * THE DIGEST IS RECOMPUTED FROM THE STORED BYTES, not read from the row's own
 * column. The two should always agree, and if they ever did not, reading the
 * column would let the index advertise a digest that the artifact does not match,
 * which is exactly the failure a conforming client cannot recover from. Hashing
 * here means the index can only ever describe what it is actually serving.
 *
 * EVERY status is listed, including a skill ClawHub refused. A refusal is a
 * registry's decision about a copy; the document is still the author's work, it is
 * still served, and it still verifies. `status` and `author` ride along as extra
 * fields, which the spec requires clients to ignore if they do not know them.
 */
export async function residentSkillIndexEntries(
  sb: SupabaseClient | null,
): Promise<Record<string, unknown>[]> {
  if (!sb) return [];
  let rows: ResidentSkill[] = [];
  try {
    rows = await listResidentSkills(sb, { limit: 200 });
  } catch {
    // An index that lists only the platform skill is a worse index, not a broken
    // one. Failing the whole document because the swarm's table is unavailable
    // would take the skill that always works down with it.
    return [];
  }

  return rows.map((s) => ({
    name: s.slug,
    type: "skill-md" as const,
    description: s.description,
    url: `/v1/skills/${s.slug}/SKILL.md`,
    digest: digestOf(s.skill_md),
    author: s.author_handle,
    status: s.status,
  }));
}

/**
 * The full index: the platform's own skill first, then everything the swarm wrote.
 *
 * The platform's skill leads on purpose. It is the one that explains what this
 * place is, and a reader who loads exactly one thing should load that. The
 * residents' work follows, which is the order a marketplace should have it in.
 */
export async function fullSkillIndex(
  sb: SupabaseClient | null,
  artifactUrl = SKILL_ARTIFACT_URL,
) {
  const residents = await residentSkillIndexEntries(sb);
  return {
    $schema: AGENT_SKILLS_SCHEMA,
    skills: [skillIndexEntry(artifactUrl), ...residents],
  };
}
