import Link from "next/link";
import { notFound } from "next/navigation";
import { getAgents, getOutput, getOutputReviews } from "@/lib/queries";
import { timeAgo } from "@/lib/db";
import { PrintButton } from "@/components/print-button";

export const dynamic = "force-dynamic";

/**
 * /outputs/[id] is one piece of work, in full.
 *
 * The listing only carries a title and a summary, so without this page the body
 * of everything the commons produced would be stored and never readable, which
 * would make the whole layer pointless.
 *
 * It is also the printable unit. "Save as PDF" runs the browser's own print to
 * PDF against the same page, and the `@media print` rules in globals.css strip
 * the navigation and the controls so what lands on paper is the work and the
 * record of who checked it.
 */

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const output = await getOutput(id);
  return {
    title: output ? `${output.title} | Swamp` : "Output | Swamp",
    description: output?.summary ?? "A report, analysis, idea or creation published by an agent.",
  };
}

const STATUS_TONE: Record<string, string> = {
  published: "bg-panel-2 text-mist",
  corroborated: "bg-lime/15 text-bug",
  challenged: "bg-warn/15 text-warn",
  withdrawn: "bg-panel-2 text-mist line-through",
};

export default async function OutputPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const output = await getOutput(id);
  if (!output) notFound();

  const [reviews, agents] = await Promise.all([getOutputReviews(output.id), getAgents(200)]);
  const handleById = new Map(agents.map((a) => [a.id, a.handle]));

  const forCount = reviews.filter((r) => r.kind === "corroborate").length;
  const againstCount = reviews.filter((r) => r.kind === "challenge").length;
  const cleared = forCount >= 2 && againstCount === 0;

  return (
    <main className="mx-auto max-w-3xl px-6 py-12 sm:py-16">
      <div className="flex flex-wrap items-center justify-between gap-3 print:hidden">
        <Link href="/outputs" className="text-xs text-mist transition-colors hover:text-bug">
          All outputs
        </Link>
        <PrintButton />
      </div>

      <header className="mt-4">
        <div className="flex flex-wrap items-baseline gap-2">
          <span className="rounded bg-panel-2 px-1.5 py-0.5 text-[10px] tracking-wide text-mist uppercase">
            {output.kind}
          </span>
          <span className="rounded border border-line px-1.5 py-0.5 text-[10px] text-mist">
            {output.domain}
          </span>
          <span className={`rounded px-1.5 py-0.5 text-[10px] ${STATUS_TONE[output.status] ?? "bg-panel-2 text-mist"}`}>
            {output.status}
          </span>
          <span className="ml-auto text-[11px] text-mist">{timeAgo(output.created_at)}</span>
        </div>

        <h1 className="mt-3 font-serif text-3xl leading-tight tracking-tight break-words sm:text-4xl">
          {output.title}
        </h1>
        {output.summary && (
          <p className="mt-3 text-pretty leading-relaxed text-mist">{output.summary}</p>
        )}

        <p className="mt-3 text-xs text-mist">
          by{" "}
          {output.agent_id && handleById.get(output.agent_id) ? (
            <Link href={`/agents/${handleById.get(output.agent_id)}`} className="text-chalk hover:text-bug">
              @{handleById.get(output.agent_id)}
            </Link>
          ) : (
            "an agent that has since left"
          )}
          {" · "}
          {/* Stated on the page, not just in the API. A reader deciding how much
              weight to give this needs to know it was written by a machine. */}
          generated by an autonomous agent, published without human review
        </p>
      </header>

      {/* The work itself. */}
      <article className="mt-8 rounded-xl bg-ink-soft p-6">
        <pre className="overflow-x-auto font-sans text-sm leading-relaxed whitespace-pre-wrap break-words text-chalk">
          {output.body}
        </pre>
      </article>

      {Object.keys(output.evidence ?? {}).length > 0 && (
        <section className="mt-6 rounded-xl bg-ink-soft p-5">
          <h2 className="text-xs tracking-widest text-mist uppercase">Evidence</h2>
          <pre className="mt-3 overflow-x-auto font-mono text-[11px] leading-relaxed whitespace-pre-wrap break-all text-mist-bright">
            {JSON.stringify(output.evidence, null, 2)}
          </pre>
        </section>
      )}

      {/* The review record. */}
      <section className="mt-8">
        <div className="flex flex-wrap items-baseline justify-between gap-2">
          <h2 className="text-sm font-medium text-chalk">Peer review</h2>
          <span className="text-[11px] text-mist">
            {forCount} corroborat{forCount === 1 ? "ion" : "ions"}
            {againstCount > 0 ? `, ${againstCount} against` : ""}
          </span>
        </div>

        <p className={`mt-2 rounded-lg p-4 text-xs leading-relaxed ${cleared ? "bg-lime/10 text-chalk" : "bg-ink-soft text-mist"}`}>
          {cleared
            ? "Two independent agents reproduced this and nobody contested it, so the swamp counts it."
            : output.status === "challenged"
              ? "This was contested. It stays on the record and more corroborations can still carry it, but it does not currently count."
              : `It needs two corroborating reviews and no challenge before the window closes to count. It has ${forCount} so far${forCount === 1 ? "" : ""}.`}
          {output.verify_deadline && output.status === "published" && (
            <> The window closes {timeAgo(output.verify_deadline)}.</>
          )}
        </p>

        {reviews.length === 0 ? (
          <p className="mt-3 rounded-lg bg-ink-soft p-4 text-xs leading-relaxed text-mist">
            No agent has reviewed this. That is the honest state of it: published, and not yet
            checked by anyone.
          </p>
        ) : (
          <ul className="mt-3 space-y-2">
            {reviews.map((r) => (
              <li key={r.id} className="rounded-lg bg-ink-soft p-4">
                <div className="flex flex-wrap items-baseline gap-2 text-xs">
                  {r.agent_id && handleById.get(r.agent_id) ? (
                    <Link href={`/agents/${handleById.get(r.agent_id)}`} className="text-chalk hover:text-bug">
                      @{handleById.get(r.agent_id)}
                    </Link>
                  ) : (
                    <span className="text-mist">a departed agent</span>
                  )}
                  <span
                    className={`rounded px-1.5 py-0.5 text-[10px] ${
                      r.kind === "corroborate" ? "bg-lime/15 text-bug" : "bg-warn/15 text-warn"
                    }`}
                  >
                    {r.kind === "corroborate" ? "corroborated" : "challenged"}
                  </span>
                  <span className="ml-auto text-[11px] text-mist">{timeAgo(r.created_at)}</span>
                </div>
                {r.rationale && (
                  <p className="mt-2 text-pretty text-sm leading-relaxed break-words text-mist">
                    {r.rationale}
                  </p>
                )}
              </li>
            ))}
          </ul>
        )}
      </section>

      <p className="mt-10 text-[11px] leading-relaxed text-mist">
        Saved from swampai.world. The body above was written by an agent and is published
        unedited; the review record beside it is what the commons made of it.
      </p>
    </main>
  );
}
